### ISSUE TITLE
Rethink Starsim parameters and API

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#301]
There are lots of quirks and inconveniences with how parameters are supplied, initialized, and validated. For example, this works:
```py
sim = ss.Sim(pars=dict(networks='random', diseases='sir'), people=ppl, demographics=demographics)
```

But these should also work:

```py
# Supply strings as kwargs
sim = ss.Sim(people=ppl, demographics=demographics, networks='random', diseases='sir')


# Supply people as a parameter
pars=dict(networks='random', diseases='sir', people=ppl, demographics=demographics)
sim = ss.Sim(pars)
```

Tasks:
- [x] Move initialization into `parameters.py`
- [x] Replace `dictmergeleft()` with `pars.update()`
- [x] Replace `par_dists` (was #354)
- [x] Reimplement `convert_plugins` (was #284)
- [x] Copy inputs flag (was #103)
- [x] Allow smarter dict-based parameter input
- [x] Link modules to sim

**Comment by cliffckerr** [comment]
Closed by #488
