### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#356]
- [x] Confirm making public with partners
- [x] Invite users to new org
- [x] Check/prune branches
- [x] Redirect starsim.org
- [x] Make public 🎉
- [x] Move repo(s) 🎉

**Comment by menriquez-IDM** [comment]
This job has been completed. There are still some tasks related to it but they are lower priority and can be completed on the new repo.
https://github.com/StarSimHub/StarSim
