### ISSUE TITLE
Make new issues and milestones

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#42]
- [x] Make this issue about making new issues
- [x] Make new issues
- [x] Sort into milestones
