### ISSUE TITLE
Refactor existing files

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#46]
- [x] Refactor base: see #54 
- [x] Refactor parameters: see #56 
- [x] Refactor sim: see #57 
- [x] Refactor people: see #59
- [x] Refactor modules: see #60
- [x] Refactor networks: see #62
- [x] Refactor results: see #64
- [x] Refactor analyzers and interventions: see #65 
- [x] Refactor other files (misc, utils, settings, etc): see #66
