### ISSUE TITLE
Rethink states/arrays again

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#652]
- [x] Move `states.py` to `arrays.py`
- [x] Make `BaseArr` or see if `Arr` can be used
- [x] Convert boolean states to `State`
- [x] Have `Arr` return `Arr` (#508)
- [x] Have `TimePar` inherit from `Arr` (#642) 
- [x] Have `Result` inherit from `Arr` (#188)
- [x] Maybe add `EnumArr` (or `IntArr`)? (#609)

**Comment by cliffckerr** [comment]
Closed by #670
